export const PERMISSIONS = {
  PROFILE_READ_SELF: 'profile.read_self',
  SCREENING_CREATE_SELF: 'screening.create_self',
  SCREENING_READ_SELF: 'screening.read_self',
  WELLBEING_USE_SELF: 'wellbeing.use_self',
  DASHBOARD_READ_ALL: 'dashboard.read_all',
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DEACTIVATE: 'users.deactivate',
  USERS_RESET_PASSWORD: 'users.reset_password',
  USERS_IMPORT: 'users.import',
  ROLES_READ: 'roles.read',
  ROLES_MANAGE: 'roles.manage',
  ROLES_ASSIGN: 'roles.assign',
  AUDIT_READ: 'audit.read',
}

export const PERMISSION_LABELS = {
  'profile.read_self': 'Lihat profil sendiri',
  'screening.create_self': 'Mengisi skrining sendiri',
  'screening.read_self': 'Lihat riwayat skrining sendiri',
  'wellbeing.use_self': 'Gunakan fitur pribadi di perangkat',
  'dashboard.read_all': 'Lihat dashboard seluruh santri',
  'users.read': 'Lihat daftar pengguna',
  'users.create': 'Tambah pengguna',
  'users.update': 'Ubah pengguna',
  'users.deactivate': 'Aktifkan/nonaktifkan pengguna',
  'users.reset_password': 'Reset sandi pengguna',
  'users.import': 'Impor pengguna dari CSV',
  'roles.read': 'Lihat role',
  'roles.manage': 'Buat dan ubah role',
  'roles.assign': 'Tetapkan role pengguna',
  'audit.read': 'Lihat audit log',
}
